// genpurposes generates the browser's request-kind catalog from usage's catalog.
package main

import (
	"encoding/json"
	"flag"
	"log"
	"os"

	"github.com/yetone/magpie/internal/usage"
)

func main() {
	out := flag.String("out", "", "JavaScript asset to write")
	flag.Parse()
	b, err := json.MarshalIndent(usage.PurposeKinds(), "", "  ")
	if err != nil {
		log.Fatal(err)
	}
	b = append([]byte("// Code generated by go generate ./internal/usage; DO NOT EDIT.\nconst REQUEST_KINDS = "), b...)
	b = append(b, ';', '\n')
	if err := os.WriteFile(*out, b, 0o644); err != nil {
		log.Fatal(err)
	}
}
